Robots:
- robot_name: "ur5_robot"
  description: "ur5_robot"
  reliability: 0.8
  urdf:
    package_name: "ur_description_robots"
    executable: "urdf/ur5_robot_2.xacro"
  manipulation:
    controller:
      package_name: "ur5_with_kinova_gripper"
      executable: "ur5_moveit_planning_execution.launch"  
      # args: "config:=true"    
      planning_groups: ["manipulator"]
    driver:
      package_name: "ur5_with_kinova_gripper"
      executable: "ur5_with_gripper_bringup.launch"
      args: "robot_ip:=192.168.1.100"
  gripper:
    controller:
      package_name: "temoto_gripper_converter"
      executable: "kinova_temoto_controller.launch"      
    driver:      
      package_name: "kinova_bringup" 
      executable: "kinova_robot.launch"
      args: "kinova_robotType:=m1n6s300"

- robot_name: "ur5_robot_sim"
  description: "ur5_robot_sim"
  reliability: 0.8
  urdf:
    package_name: "ur_description_robots"
    executable: "urdf/ur5_robot_2.xacro"
  manipulation:
    controller:
      package_name: "ur5_with_kinova_gripper"
      executable: "demo.launch"  
      # args: "config:=true"    
      planning_groups: ["manipulator"]
    driver:
      package_name: "ur5_with_kinova_gripper"
      executable: "demo.launch"
  gripper:
    controller:
      package_name: "temoto_gripper_converter"
      executable: "kinova_temoto_controller.launch"      
    driver:      
      package_name: "kinova_bringup" 
      executable: "kinova_robot.launch"
      args: "kinova_robotType:=m1n6s300"
