Robots:
- robot_name: "ur5_robot"
  description: "ur5_robot"
  reliability: 0.8
  urdf:
    package_name: "ur_description_robots"
    executable: "urdf/ur5_with_base.xacro"
  manipulation:
    controller:
      package_name: "ur5_v2_moveit_config"
      executable: "ur5_moveit_planning_execution.launch"  
      # args: "config:=true"    
      planning_groups: ["manipulator"]
    driver:
      package_name: "ur_robot_driver"
      executable: "ur5_modified_bringup.launch"
      args: "robot_ip:=192.168.1.100"
