Robots:
- robot_name: "clearbot"
  description: "clearbot"
  reliability: 0.8
  urdf:
    package_name: "robotont_description"
    executable: "xacro/main.urdf.xacro"
  navigation:
    controller:
      package_name: "robotont_ws"
      executable: "temoto_nav.launch"
      global_planner: "navfn/NavfnROS"        #/move_base/DWAPlannerROS/global_plan
      local_planner: "dwa_local_planner/DWAPlannerROS"
                                              #dwa_local_planner/DWAPlannerROS
    driver:
      package_name: "robotont_ws" 
      executable: "driver_temoto.launch"      
